#cloud-config
apt_update: true
apt_upgrade: true
runcmd:
  - |
    # install k3s, direnv, task
    curl -sfL https://get.k3s.io | sh -
    curl -sfL https://direnv.net/install.sh | bash
    snap install task --classic
    echo "OPS_CLOUD_INIT_VER=1" >>/etc/environment
  - |
    # set home and user
    USR="$(getent passwd 1000 | awk -F: '{print $1}')"
    HOME="/home/$USR"
    # access k3s
    mkdir -p "$HOME/.kube"
    cp /etc/rancher/k3s/k3s.yaml "$HOME/.kube/config"
    echo "export KUBECONFIG=/home/$USR/.kube/config" >>$HOME/.bashrc
    # use direnv for autoinit 
    echo 'eval "$(direnv hook bash)"' >>$HOME/.bashrc
    # install nix
    curl -L https://nixos.org/nix/install | sudo -u "$USR"  sh -s -- --no-daemon
    # get openserverless sources
    cd $HOME
    git clone https://github.com/nuvolaris/openserverless --recurse-submodules
    cd  $HOME/openserverless ; chmod +x sync-branch.sh ; ./sync-branch.sh
    # add aliases
    echo "source $HOME/openserverless/aliases" >>$HOME/.bashrc
    # change owner to everything
    chown -Rvf "$USR" "$HOME"
    # allow direnv for submodules
    sudo -u $USR direnv allow $HOME/openserverless/cli
    sudo -u $USR direnv allow $HOME/openserverless/operator
    sudo -u $USR direnv allow $HOME/openserverless/site
     
 
